### ISSUE TITLE
Review z-index for Modal

### ISSUE THREAD

**Issue by mbohal** [react-ui-org/react-ui#471]
When migrating to MkDocs/Docoff  based docs (https://github.com/react-ui-org/react-ui/pull/440) an issue appeared with `z-index` preference. The MkDocs sticky header covers `Modal` which is wrong.

![image](https://github.com/react-ui-org/react-ui/assets/4589176/a416fb53-ffff-4435-a586-ad071cc09634)

Expected behavior: `Modal` covers the sticky header, not vice versa.

How to reproduce:
1. Go to http://localhost:8000/components/Modal/#position
2. Modify the code by adding the attribute `preventScrollUnderneath="off"` to the `Modal`  component
3. Click the `Launch modal at top` button
4. Scroll to the top of the page

**Comment by hubacekj** [comment]
It is caused by different stacking contexts for the sticky header and for the `Modal`. Both have their own stacking contexts caused by setting `position: sticky` and `transform` css property respectively. There are two immediate (one future) solutions:
1. Stop using transform property and replace it with negative margins (requires a javascript resize listener - therefore I wouldn't prefer it)
2. Use portal above all other elements in the documentation
(3.)  Use a native `dialog` element

**Comment by adamkudrna** [comment]
Relates to #461.

**Comment by adamkudrna** [comment]
Just adding a couple of screenshots:

![Image](https://github.com/react-ui-org/react-ui/assets/5614085/ba9cdb1b-ce66-4b06-ad40-d6a66bf7c318)
![Image](https://github.com/react-ui-org/react-ui/assets/5614085/5110100c-ff82-49e3-855b-828863959cae)
![Image](https://github.com/react-ui-org/react-ui/assets/5614085/f8c3a28e-e7ea-479f-9703-8f3bcaba9074)
