### ISSUE TITLE
`Modal` component `preventScrollUnderneath` prop not working

### ISSUE THREAD

**Issue by mbohal** [react-ui-org/react-ui#472]
When migrating to MkDocs/Docoff based docs (https://github.com/react-ui-org/react-ui/pull/440) an issue with the prop `preventScrollUnderneath` in the `Modal` component appeared.

It seems that the default scroll prevention does not work with the MkDocs platform:

1. Scrolling is possible when `preventScrollUnderneath="default"`
2. In Chrome (FF is OK) there is extra padding in the top right corner when `Modal` is open:
      ![image](https://github.com/react-ui-org/react-ui/assets/4589176/65986232-c0d5-465e-ac00-887d083e4f66)

**Comment by hubacekj** [comment]
The reason why `preventScrollUnderneath="default"` does not work is that we prevent scrolling by default on the `body` element. This documentation, however, has the scroll on the `<html>` element. I tried to replace the `body` with the `documentElement` in the hook and it worked as expected.

I think that leaving the scroll prevention by default on the `body` element is actually the correct way, which leaves us with 2 options:
1. Make changes to the documentation so that the scrolling is on the body
2. Add custom `preventScrollUnderneath` object to all the modals with basically a 1 to 1 copy of the code in the `useModalScrollPrevention` `if (preventScrollUnderneath === 'default'` branch
